/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props: any) {
  const group = useRef()
  const { nodes, materials }: any = useGLTF('/interior-test.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group scale={[2.84, 1.3, 6.01]}>
        <mesh geometry={nodes.Cube002.geometry} material={materials.WoodFlooringMerbauBrickBondNatural001_3K} />
        <mesh geometry={nodes.Cube002_1.geometry} material={materials.Wall} />
      </group>
    </group>
  )
}

useGLTF.preload('/interior-test.gltf')
